# Generated by Django 3.2.22 on 2023-10-15 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='spread_sheets/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(blank=True, max_length=250, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=250, null=True)),
                ('last_modified_on', models.DateTimeField(blank=True, null=True)),
                ('result', models.DecimalField(decimal_places=3, max_digits=15)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='filemanagement.filerequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
