# Generated by Django 3.2.22 on 2023-10-15 11:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0002_calculationresult_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='errors',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
